/* ==========================================================
 * bootstrap-formhelpers-countries.en_US.js
 * https://github.com/vlamanna/BootstrapFormHelpers
 * ==========================================================
 * Copyright 2012 Vincent Lamanna
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ========================================================== */

 var BFHCountriesList = {
"1" : {"name": "Afghanistan","code":"AF"},
"2" : {"name": "Albania","code":"AL"},
"3" : {"name": "Algeria","code":"DZ"},
"4" : {"name": "American Samoa","code":"AS"},
"5" : {"name": "Andorra","code":"AD"},
"6" : {"name": "Angola","code":"AO"},
"7" : {"name": "Anguilla","code":"AI"},
"8" : {"name": "Antarctica","code":"AQ"},
"9" : {"name": "Antigua and Barbuda","code":"AG"},
"10" : {"name": "Argentina","code":"AR"},
"11" : {"name": "Armenia","code":"AM"},
"12" : {"name": "Aruba","code":"AW"},
"13" : {"name": "Australia","code":"AU"},
"14" : {"name": "Austria","code":"AT"},
"15" : {"name": "Azerbaijan","code":"AZ"},
"16" : {"name": "Bahamas","code":"BS"},
"17" : {"name": "Bahrain","code":"BH"},
"18" : {"name": "Bangladesh","code":"BD"},
"19" : {"name": "Barbados","code":"BB"},
"20" : {"name": "Belarus","code":"BY"},
"21" : {"name": "Belgium","code":"BE"},
"22" : {"name": "Belize","code":"BZ"},
"23" : {"name": "Benin","code":"BJ"},
"24" : {"name": "Bermuda","code":"BM"},
"25" : {"name": "Bhutan","code":"BT"},
"26" : {"name": "Bolivia","code":"BO"},
"27" : {"name": "Bosnia and Herzegowina","code":"BA"},
"28" : {"name": "Botswana","code":"BW"},
"29" : {"name": "Bouvet Island","code":"BV"},
"30" : {"name": "Brazil","code":"BR"},
"31" : {"name": "British Indian Ocean Territory","code":"IO"},
"32" : {"name": "Brunei Darussalam","code":"BN"},
"33" : {"name": "Bulgaria","code":"BG"},
"34" : {"name": "Burkina Faso","code":"BF"},
"35" : {"name": "Burundi","code":"BI"},
"36" : {"name": "Cambodia","code":"KH"},
"37" : {"name": "Cameroon","code":"CM"},
"38" : {"name": "Canada","code":"CA"},
"39" : {"name": "Cape Verde","code":"CV"},
"40" : {"name": "Cayman Islands","code":"KY"},
"41" : {"name": "Central African Republic","code":"CF"},
"42" : {"name": "Chad","code":"TD"},
"43" : {"name": "Chile","code":"CL"},
"44" : {"name": "China","code":"CN"},
"45" : {"name": "Christmas Island","code":"CX"},
"46" : {"name": "Cocos (Keeling) Islands","code":"CC"},
"47" : {"name": "Colombia","code":"CO"},
"48" : {"name": "Comoros","code":"KM"},
"49" : {"name": "Congo","code":"CG"},
"50" : {"name": "Cook Islands","code":"CK"},
"51" : {"name": "Costa Rica","code":"CR"},
"52" : {"name": "Cote D'Ivoire","code":"CI"},
"53" : {"name": "Croatia","code":"HR"},
"54" : {"name": "Cuba","code":"CU"},
"55" : {"name": "Cyprus","code":"CY"},
"56" : {"name": "Czech Republic","code":"CZ"},
"57" : {"name": "Denmark","code":"DK"},
"58" : {"name": "Djibouti","code":"DJ"},
"59" : {"name": "Dominica","code":"DM"},
"60" : {"name": "Dominican Republic","code":"DO"},
"61" : {"name": "East Timor","code":"TP"},
"62" : {"name": "Ecuador","code":"EC"},
"63" : {"name": "Egypt","code":"EG"},
"64" : {"name": "El Salvador","code":"SV"},
"65" : {"name": "Equatorial Guinea","code":"GQ"},
"66" : {"name": "Eritrea","code":"ER"},
"67" : {"name": "Estonia","code":"EE"},
"68" : {"name": "Ethiopia","code":"ET"},
"69" : {"name": "Falkland Islands (Malvinas)","code":"FK"},
"70" : {"name": "Faroe Islands","code":"FO"},
"71" : {"name": "Fiji","code":"FJ"},
"72" : {"name": "Finland","code":"FI"},
"73" : {"name": "France","code":"FR"},
"74" : {"name": "France, Metropolitan","code":"FX"},
"75" : {"name": "French Guiana","code":"GF"},
"76" : {"name": "French Polynesia","code":"PF"},
"77" : {"name": "French Southern Territories","code":"TF"},
"78" : {"name": "Gabon","code":"GA"},
"79" : {"name": "Gambia","code":"GM"},
"80" : {"name": "Georgia","code":"GE"},
"81" : {"name": "Germany","code":"DE"},
"82" : {"name": "Ghana","code":"GH"},
"83" : {"name": "Gibraltar","code":"GI"},
"84" : {"name": "Greece","code":"GR"},
"85" : {"name": "Greenland","code":"GL"},
"86" : {"name": "Grenada","code":"GD"},
"87" : {"name": "Guadeloupe","code":"GP"},
"88" : {"name": "Guam","code":"GU"},
"89" : {"name": "Guatemala","code":"GT"},
"90" : {"name": "Guinea","code":"GN"},
"91" : {"name": "Guinea-bissau","code":"GW"},
"92" : {"name": "Guyana","code":"GY"},
"93" : {"name": "Haiti","code":"HT"},
"94" : {"name": "Heard and Mc Donald Islands","code":"HM"},
"95" : {"name": "Honduras","code":"HN"},
"96" : {"name": "Hong Kong","code":"HK"},
"97" : {"name": "Hungary","code":"HU"},
"98" : {"name": "Iceland","code":"IS"},
"99" : {"name": "India","code":"IN"},
"100" : {"name": "Indonesia","code":"ID"},
"101" : {"name": "Iran (Islamic Republic of)","code":"IR"},
"102" : {"name": "Iraq","code":"IQ"},
"103" : {"name": "Ireland","code":"IE"},
"104" : {"name": "Israel","code":"IL"},
"105" : {"name": "Italy","code":"IT"},
"106" : {"name": "Jamaica","code":"JM"},
"107" : {"name": "Japan","code":"JP"},
"108" : {"name": "Jordan","code":"JO"},
"109" : {"name": "Kazakhstan","code":"KZ"},
"110" : {"name": "Kenya","code":"KE"},
"111" : {"name": "Kiribati","code":"KI"},
"112" : {"name": "Korea, Democratic People's Republic of","code":"KP"},
"113" : {"name": "Korea, Republic of","code":"KR"},
"114" : {"name": "Kuwait","code":"KW"},
"115" : {"name": "Kyrgyzstan","code":"KG"},
"116" : {"name": "Lao People's Democratic Republic","code":"LA"},
"117" : {"name": "Latvia","code":"LV"},
"118" : {"name": "Lebanon","code":"LB"},
"119" : {"name": "Lesotho","code":"LS"},
"120" : {"name": "Liberia","code":"LR"},
"121" : {"name": "Libyan Arab Jamahiriya","code":"LY"},
"122" : {"name": "Liechtenstein","code":"LI"},
"123" : {"name": "Lithuania","code":"LT"},
"124" : {"name": "Luxembourg","code":"LU"},
"125" : {"name": "Macau","code":"MO"},
"126" : {"name": "Macedonia, The Former Yugoslav Republic of","code":"MK"},
"127" : {"name": "Madagascar","code":"MG"},
"128" : {"name": "Malawi","code":"MW"},
"129" : {"name": "Malaysia","code":"MY"},
"130" : {"name": "Maldives","code":"MV"},
"131" : {"name": "Mali","code":"ML"},
"132" : {"name": "Malta","code":"MT"},
"133" : {"name": "Marshall Islands","code":"MH"},
"134" : {"name": "Martinique","code":"MQ"},
"135" : {"name": "Mauritania","code":"MR"},
"136" : {"name": "Mauritius","code":"MU"},
"137" : {"name": "Mayotte","code":"YT"},
"138" : {"name": "Mexico","code":"MX"},
"139" : {"name": "Micronesia, Federated States of","code":"FM"},
"140" : {"name": "Moldova, Republic of","code":"MD"},
"141" : {"name": "Monaco","code":"MC"},
"142" : {"name": "Mongolia","code":"MN"},
"143" : {"name": "Montserrat","code":"MS"},
"144" : {"name": "Morocco","code":"MA"},
"145" : {"name": "Mozambique","code":"MZ"},
"146" : {"name": "Myanmar","code":"MM"},
"147" : {"name": "Namibia","code":"NA"},
"148" : {"name": "Nauru","code":"NR"},
"149" : {"name": "Nepal","code":"NP"},
"150" : {"name": "Netherlands","code":"NL"},
"151" : {"name": "Netherlands Antilles","code":"AN"},
"152" : {"name": "New Caledonia","code":"NC"},
"153" : {"name": "New Zealand","code":"NZ"},
"154" : {"name": "Nicaragua","code":"NI"},
"155" : {"name": "Niger","code":"NE"},
"156" : {"name": "Nigeria","code":"NG"},
"157" : {"name": "Niue","code":"NU"},
"158" : {"name": "Norfolk Island","code":"NF"},
"159" : {"name": "Northern Mariana Islands","code":"MP"},
"160" : {"name": "Norway","code":"NO"},
"161" : {"name": "Oman","code":"OM"},
"162" : {"name": "Pakistan","code":"PK"},
"163" : {"name": "Palau","code":"PW"},
"164" : {"name": "Panama","code":"PA"},
"165" : {"name": "Papua New Guinea","code":"PG"},
"166" : {"name": "Paraguay","code":"PY"},
"167" : {"name": "Peru","code":"PE"},
"168" : {"name": "Philippines","code":"PH"},
"169" : {"name": "Pitcairn","code":"PN"},
"170" : {"name": "Poland","code":"PL"},
"171" : {"name": "Portugal","code":"PT"},
"172" : {"name": "Puerto Rico","code":"PR"},
"173" : {"name": "Qatar","code":"QA"},
"174" : {"name": "Reunion","code":"RE"},
"175" : {"name": "Romania","code":"RO"},
"176" : {"name": "Russian Federation","code":"RU"},
"177" : {"name": "Rwanda","code":"RW"},
"178" : {"name": "Saint Kitts and Nevis","code":"KN"},
"179" : {"name": "Saint Lucia","code":"LC"},
"180" : {"name": "Saint Vincent and the Grenadines","code":"VC"},
"181" : {"name": "Samoa","code":"WS"},
"182" : {"name": "San Marino","code":"SM"},
"183" : {"name": "São Tomé and Príncipe","code":"ST"},
"184" : {"name": "Saudi Arabia","code":"SA"},
"185" : {"name": "Senegal","code":"SN"},
"186" : {"name": "Seychelles","code":"SC"},
"187" : {"name": "Sierra Leone","code":"SL"},
"188" : {"name": "Singapore","code":"SG"},
"189" : {"name": "Slovakia (Slovak Republic)","code":"SK"},
"190" : {"name": "Slovenia","code":"SI"},
"191" : {"name": "Solomon Islands","code":"SB"},
"192" : {"name": "Somalia","code":"SO"},
"193" : {"name": "South Africa","code":"ZA"},
"194" : {"name": "South Georgia and the South Sandwich Islands","code":"GS"},
"195" : {"name": "Spain","code":"ES"},
"196" : {"name": "Sri Lanka","code":"LK"},
"197" : {"name": "St. Helena","code":"SH"},
"198" : {"name": "St. Pierre and Miquelon","code":"PM"},
"199" : {"name": "Sudan","code":"SD"},
"200" : {"name": "Suriname","code":"SR"},
"201" : {"name": "Svalbard and Jan Mayen Islands","code":"SJ"},
"202" : {"name": "Swaziland","code":"SZ"},
"203" : {"name": "Sweden","code":"SE"},
"204" : {"name": "Switzerland","code":"CH"},
"205" : {"name": "Syrian Arab Republic","code":"SY"},
"206" : {"name": "Taiwan","code":"TW"},
"207" : {"name": "Tajikistan","code":"TJ"},
"208" : {"name": "Tanzania, United Republic of","code":"TZ"},
"209" : {"name": "Thailand","code":"TH"},
"210" : {"name": "Togo","code":"TG"},
"211" : {"name": "Tokelau","code":"TK"},
"212" : {"name": "Tonga","code":"TO"},
"213" : {"name": "Trinidad and Tobago","code":"TT"},
"214" : {"name": "Tunisia","code":"TN"},
"215" : {"name": "Turkey","code":"TR"},
"216" : {"name": "Turkmenistan","code":"TM"},
"217" : {"name": "Turks and Caicos Islands","code":"TC"},
"218" : {"name": "Tuvalu","code":"TV"},
"219" : {"name": "Uganda","code":"UG"},
"220" : {"name": "Ukraine","code":"UA"},
"221" : {"name": "United Arab Emirates","code":"AE"},
"222" : {"name": "United Kingdom","code":"GB"},
"223" : {"name": "United States","code":"US"},
"224" : {"name": "United States Minor Outlying Islands","code":"UM"},
"225" : {"name": "Uruguay","code":"UY"},
"226" : {"name": "Uzbekistan","code":"UZ"},
"227" : {"name": "Vanuatu","code":"VU"},
"228" : {"name": "Vatican City State (Holy See)","code":"VA"},
"229" : {"name": "Venezuela","code":"VE"},
"230" : {"name": "Viet Nam","code":"VN"},
"231" : {"name": "Virgin Islands (British)","code":"VG"},
"232" : {"name": "Virgin Islands (U.S.)","code":"VI"},
"233" : {"name": "Wallis and Futuna Islands","code":"WF"},
"234" : {"name": "Western Sahara","code":"EH"},
"235" : {"name": "Yemen","code":"YE"},
"236" : {"name": "Yugoslavia","code":"YU"},
"237" : {"name": "Zaire","code":"ZR"},
"238" : {"name": "Zambia","code":"ZM"},
"239" : {"name": "Zimbabwe","code":"ZW"}
 } 